"""add whatsapp_conversation to process_candidates

Revision ID: 093babcf6bb6
Revises: aa6557c28990
Create Date: 2026-07-09 07:32:21.987467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '093babcf6bb6'
down_revision: Union[str, Sequence[str], None] = 'aa6557c28990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('process_candidates', sa.Column('whatsapp_conversation', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('process_candidates', 'whatsapp_conversation')
    # ### end Alembic commands ###
