"""add transcript_turns to profiling_runs

Revision ID: 590a221e10f4
Revises: d4a4444a2ab1
Create Date: 2026-07-11 19:59:40.738991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '590a221e10f4'
down_revision: Union[str, Sequence[str], None] = 'd4a4444a2ab1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTA: se quito un `drop_column('process_candidates', 'whatsapp_conversation')`
    # autogenerado — esa columna es real (feature de memoria de WhatsApp en otra rama
    # que aun no esta en los modelos locales), no se debe borrar desde esta migracion.
    op.add_column('profiling_runs', sa.Column('transcript_turns', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiling_runs', 'transcript_turns')
    # ### end Alembic commands ###
