"""add voice call tracking and config columns

Revision ID: aa6557c28990
Revises: fa2683c60fb2
Create Date: 2026-07-07 20:46:29.846221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa6557c28990'
down_revision: Union[str, Sequence[str], None] = 'fa2683c60fb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hiring_processes', sa.Column('voice_override_agent_id', sa.String(length=100), nullable=True))
    op.add_column('hiring_processes', sa.Column('voice_override_system_prompt', sa.TEXT(), nullable=True))
    op.add_column('hiring_processes', sa.Column('voice_override_first_message', sa.TEXT(), nullable=True))
    op.add_column('hiring_processes', sa.Column('voice_override_language', sa.String(length=10), nullable=True))
    op.add_column('hiring_processes', sa.Column('voice_override_llm_model', sa.String(length=50), nullable=True))
    op.add_column('hiring_processes', sa.Column('voice_override_voice_id', sa.String(length=100), nullable=True))
    op.add_column('hiring_processes', sa.Column('voice_override_tts_stability', sa.Float(), nullable=True))
    op.add_column('hiring_processes', sa.Column('voice_override_tts_speed', sa.Float(), nullable=True))
    op.add_column('hiring_processes', sa.Column('voice_override_tts_similarity_boost', sa.Float(), nullable=True))
    op.add_column('profiling_runs', sa.Column('twilio_call_sid', sa.String(length=64), nullable=True))
    op.add_column('profiling_runs', sa.Column('elevenlabs_conversation_id', sa.String(length=64), nullable=True))
    op.add_column('profiling_runs', sa.Column('amd_result', sa.String(length=30), nullable=True))
    op.add_column('profiling_runs', sa.Column('twilio_status_detail', sa.String(length=30), nullable=True))
    op.add_column('profiling_runs', sa.Column('transcript_summary', sa.TEXT(), nullable=True))
    op.create_index('uq_profiling_runs_elevenlabs_conversation_id', 'profiling_runs', ['elevenlabs_conversation_id'], unique=True, postgresql_where=sa.text('elevenlabs_conversation_id IS NOT NULL'))
    op.create_index('uq_profiling_runs_twilio_call_sid', 'profiling_runs', ['twilio_call_sid'], unique=True, postgresql_where=sa.text('twilio_call_sid IS NOT NULL'))
    op.add_column('question_sets', sa.Column('default_agent_id', sa.String(length=100), nullable=True))
    op.add_column('question_sets', sa.Column('default_system_prompt', sa.TEXT(), nullable=True))
    op.add_column('question_sets', sa.Column('default_first_message', sa.TEXT(), nullable=True))
    op.add_column('question_sets', sa.Column('default_language', sa.String(length=10), nullable=True))
    op.add_column('question_sets', sa.Column('default_llm_model', sa.String(length=50), nullable=True))
    op.add_column('question_sets', sa.Column('default_voice_id', sa.String(length=100), nullable=True))
    op.add_column('question_sets', sa.Column('default_tts_stability', sa.Float(), nullable=True))
    op.add_column('question_sets', sa.Column('default_tts_speed', sa.Float(), nullable=True))
    op.add_column('question_sets', sa.Column('default_tts_similarity_boost', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question_sets', 'default_tts_similarity_boost')
    op.drop_column('question_sets', 'default_tts_speed')
    op.drop_column('question_sets', 'default_tts_stability')
    op.drop_column('question_sets', 'default_voice_id')
    op.drop_column('question_sets', 'default_llm_model')
    op.drop_column('question_sets', 'default_language')
    op.drop_column('question_sets', 'default_first_message')
    op.drop_column('question_sets', 'default_system_prompt')
    op.drop_column('question_sets', 'default_agent_id')
    op.drop_index('uq_profiling_runs_twilio_call_sid', table_name='profiling_runs', postgresql_where=sa.text('twilio_call_sid IS NOT NULL'))
    op.drop_index('uq_profiling_runs_elevenlabs_conversation_id', table_name='profiling_runs', postgresql_where=sa.text('elevenlabs_conversation_id IS NOT NULL'))
    op.drop_column('profiling_runs', 'transcript_summary')
    op.drop_column('profiling_runs', 'twilio_status_detail')
    op.drop_column('profiling_runs', 'amd_result')
    op.drop_column('profiling_runs', 'elevenlabs_conversation_id')
    op.drop_column('profiling_runs', 'twilio_call_sid')
    op.drop_column('hiring_processes', 'voice_override_tts_similarity_boost')
    op.drop_column('hiring_processes', 'voice_override_tts_speed')
    op.drop_column('hiring_processes', 'voice_override_tts_stability')
    op.drop_column('hiring_processes', 'voice_override_voice_id')
    op.drop_column('hiring_processes', 'voice_override_llm_model')
    op.drop_column('hiring_processes', 'voice_override_language')
    op.drop_column('hiring_processes', 'voice_override_first_message')
    op.drop_column('hiring_processes', 'voice_override_system_prompt')
    op.drop_column('hiring_processes', 'voice_override_agent_id')
    # ### end Alembic commands ###
