"""add normalized_cv_url to candidates

Revision ID: b1eba246e785
Revises: 8bdf9ed89e3a
Create Date: 2026-06-24 10:19:38.267771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1eba246e785'
down_revision: Union[str, Sequence[str], None] = '8bdf9ed89e3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('normalized_cv_url', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'normalized_cv_url')
    # ### end Alembic commands ###
